### ISSUE TITLE
Where is software serial code?

### ISSUE THREAD

**Issue by gkzsolt** [BPI-STEAM/MicroPython-Samples#4]
Hi,

I am looking for a software serial micropython implementation, what you apparently have. However, in 02.inputs/serial.py I see only 'import serial', and it's not clear what module are you referring to. Can you help, please?

Thanks,
   Zsolt

**Comment by junhuanchen** [comment]
https://github.com/junhuanchen/esp-idf-software-serial/blob/master/serial.py
